name: Deploy

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Install Kamal
        run: gem install kamal

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          
          # Configure SSH to skip host key checking for deployment
          # This is acceptable for CI/CD as we're using our own servers
          cat >> ~/.ssh/config <<EOF
          Host *
            StrictHostKeyChecking no
            UserKnownHostsFile=/dev/null
            LogLevel ERROR
          EOF
          chmod 600 ~/.ssh/config

      - name: Create master.key file
        run: |
          mkdir -p config
          echo -n "${{ secrets.RAILS_MASTER_KEY }}" > config/master.key

      - name: Deploy with Kamal
        run: |
          kamal deploy
        env:
          GHCR_PAT: ${{ secrets.GHCR_PAT }}
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          PRODUCTION_POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          PRODUCTION_POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}