name: RuboCop

on:
  push:
  pull_request:

jobs:
  rubocop:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: .ruby-version
        bundler-cache: true # runs 'bundle install' and caches installed gems

    - name: Run RuboCop
      run: bundle exec rubocop --parallel --format github